INSERT INTO countries (name, name_local, iso_code_2, iso_code_3, is_active) VALUES
('Argentina', 'Argentina', 'AR', 'ARG', true),
('Bolivia', 'Bolivia', 'BO', 'BOL', true),
('Brazil', 'Brasil', 'BR', 'BRA', true),
('Canada', 'Canada', 'CA', 'CAN', true),
('Chile', 'Chile', 'CL', 'CHL', true),
('Colombia', 'Colombia', 'CO', 'COL', true),
('Costa Rica', 'Costa Rica', 'CR', 'CRI', true),
('Cuba', 'Cuba', 'CU', 'CUB', true),
('Dominican Republic', 'República Dominicana', 'DO', 'DOM', true),
('Ecuador', 'Ecuador', 'EC', 'ECU', true),
('El Salvador', 'El Salvador', 'SV', 'SLV', true),
('Guatemala', 'Guatemala', 'GT', 'GTM', true),
('Honduras', 'Honduras', 'HN', 'HND', true),
('Mexico', 'México', 'MX', 'MEX', true),
('Nicaragua', 'Nicaragua', 'NI', 'NIC', true),
('Panama', 'Panamá', 'PA', 'PAN', true),
('Paraguay', 'Paraguay', 'PY', 'PRY', true),
('Peru', 'Perú', 'PE', 'PER', true),
('United States', 'United States', 'US', 'USA', true),
('Uruguay', 'Uruguay', 'UY', 'URY', true),
('Venezuela', 'Venezuela', 'VE', 'VEN', true);
